version: '3'
services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
     - .:/code
    ports:
    - "8002:8000"
    depends_on:
        - db
  db:
      image: postgres:16
      ports:
        - "54322:5432"
      env_file:
        - .env
      volumes:
           - postgres_data:/var/lib/postgresql/data/
      environment:
            - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
      postgres_data: